update

diff --git a/.github/workflows/cypress-tests.yml b/.github/workflows/cypress-tests.yml
--- a/.github/workflows/cypress-tests.yml
+++ b/.github/workflows/cypress-tests.yml
@@ -24,12 +24,15 @@ jobs:
       - name: Run Cypress tests
         run: npm run test:all:chrome:report
         working-directory: ./Week-10-cy-automation
+      - name: Generate Mochawesome report
+        run: npm run test:merge-reports-chrome && npm run test:generate-report-chrome || echo "Report generation failed"
+        working-directory: ./Week-10-cy-automation
       - name: Upload Mochawesome reports chrome
         uses: actions/upload-artifact@v4
         with:
           name: mochawesome-report-chrome
           path: ./Week-10-cy-automation/mochawesome-report-chrome/
-        if: always() 
+        if: always()
 
   Cypress-Run-Firefox:
     runs-on: macos-latest
@@ -47,12 +50,12 @@ jobs:
       - name: Run Cypress tests
         run: npm run test:all:firefox:report
         working-directory: ./Week-10-cy-automation
+      - name: Generate Mochawesome report
+        run: npm run test:merge-reports-firefox && npm run test:generate-report-firefox || echo "Report generation failed"
+        working-directory: ./Week-10-cy-automation
       - name: Upload Mochawesome reports firefox
         uses: actions/upload-artifact@v4
         with:
           name: mochawesome-report-firefox
           path: ./Week-10-cy-automation/mochawesome-report-firefox/
-        if: always() 
-
-  
-
+        if: always()
